// Generated by scripts/lnplabrador.py sync-backend from scripts/para1.py.
// Do not edit this file directly; edit para1.py and run sync-backend.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace icicle::labrador::backend_config {

inline constexpr uint32_t RING_DEGREE = 64U;
inline constexpr uint64_t RING_MODULUS = 1099511627581ULL;
inline constexpr uint64_t RING_MODULUS_HALF = 549755813790ULL;
inline constexpr uint64_t RING_MODULUS_SQRT_FLOOR = 1048575ULL;

inline constexpr size_t SECURITY_BITS = 128U;
inline constexpr size_t JL_ROWS = 256U;
inline constexpr size_t AGGREGATION_ROUNDS = 4U;
inline constexpr size_t DEFAULT_RECURSIONS = 1U;
inline constexpr size_t MAX_RECURSIONS = 8U;
inline constexpr long double ROOT_HERMITE_DELTA = 1.00444L;
inline constexpr size_t BASE_MSIS_RANK = 24U;

inline constexpr uint32_t CHALLENGE_ZERO_COEFFICIENTS = 23U;
inline constexpr uint32_t CHALLENGE_UNIT_COEFFICIENTS = 31U;
inline constexpr uint32_t CHALLENGE_DOUBLE_COEFFICIENTS = 10U;
inline constexpr uint64_t CHALLENGE_OPERATOR_NORM_BOUND = 15ULL;
inline constexpr uint64_t CHALLENGE_TAU = 71ULL;

inline constexpr uint64_t MAX_ARTIFACT_BYTES = 1073741824ULL;
inline constexpr uint64_t MAX_PROOF_BYTES = 67108864ULL;
inline constexpr size_t MAX_RUNTIME_POLYNOMIALS = 8388608U;
inline constexpr size_t MAX_SPLIT_PARTS = 256U;
inline constexpr size_t EXTRACTION_SLACK_DENOMINATOR = 30U;
inline constexpr size_t MODULAR_JL_DENOMINATOR = 125U;

struct PaperScheduleEntry {
  size_t n;
  size_t r;
  size_t kappa;
  size_t kappa1;
  size_t kappa2;
  size_t nu_to_next;
  size_t mu_to_next;
  bool section_5_6_tail;
};

inline constexpr std::array<PaperScheduleEntry, 7> PAPER_SCHEDULE{{
  PaperScheduleEntry{27595U, 38U, 17U, 6U, 6U, 8U, 5U, false},
  PaperScheduleEntry{3450U, 21U, 14U, 5U, 5U, 3U, 4U, false},
  PaperScheduleEntry{1150U, 10U, 12U, 4U, 4U, 2U, 3U, false},
  PaperScheduleEntry{575U, 7U, 11U, 4U, 4U, 2U, 3U, false},
  PaperScheduleEntry{290U, 7U, 10U, 4U, 4U, 1U, 3U, false},
  PaperScheduleEntry{290U, 5U, 10U, 3U, 3U, 2U, 2U, true},
  PaperScheduleEntry{153U, 4U, 12U, 4U, 4U, 0U, 0U, false}
}};

inline constexpr char PARAMETER_SHA256[] = "a306928a989f6f3abc6f4fd9d920f1140b2d4262dc845119ed406908d16e3cf5";

} // namespace icicle::labrador::backend_config
