#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

// Deterministic, non-secret seven-execution LaBRADOR sample using the fixed
// schedule for a binary-R1CS below 2^23 constraints.
//
// The concrete witness is represented compactly: all r*n ring polynomials are
// zero except WITNESS_NONZERO_POLYNOMIAL, coefficient
// WITNESS_NONZERO_COEFFICIENT, whose centered value is
// WITNESS_NONZERO_VALUE.  This avoids writing a ~1,048,610-polynomial C++
// initializer while still defining every witness coefficient unambiguously.
// The public relation contains one identically-zero equality, so this witness
// satisfies it exactly.  This is an executable principal-relation sample, not
// the user's unavailable full numeric binary-R1CS matrices A/B/C.
// Run it with: ./build/src/lab_runner CPU --sample-seven-level
namespace labrador_sample7 {

inline constexpr size_t SAMPLE_RING_DEGREE = 64;
inline constexpr uint64_t SAMPLE_RING_MODULUS = 1099511627581ULL; // 2^40 - 195

inline constexpr size_t R = 38;
inline constexpr size_t N = 27595;
// Strict Section 6 capacity bound sqrt(2*(2^23+3*2^23)+1), rather than the
// much looser sqrt(q) value previously used by the recurrence planner.
inline constexpr double BETA = 8192.000061035156;
inline constexpr size_t KAPPA = 10;
inline constexpr size_t KAPPA1 = 4;
inline constexpr size_t KAPPA2 = 4;
inline constexpr uint32_t BASE1 = 11;
inline constexpr uint32_t BASE2 = 6;
inline constexpr uint32_t BASE3 = 11;
inline constexpr size_t JL_ROWS = 256;
inline constexpr size_t AGGREGATION_ROUNDS = 4;
inline constexpr size_t RECURSIVE_EXECUTIONS = 7;

inline constexpr size_t WITNESS_POLYNOMIALS = R * N;
inline constexpr size_t WITNESS_NONZERO_POLYNOMIAL = 0;
inline constexpr size_t WITNESS_NONZERO_COEFFICIENT = 0;
inline constexpr int64_t WITNESS_NONZERO_VALUE = 1;
inline constexpr double WITNESS_L2_NORM = 1.0;

// The displayed planning ranks are generated by the local root-Hermite
// fallback.  In particular, they are not a concrete Module-SIS-estimator
// certificate for the full application.
inline constexpr bool CONCRETE_SECURITY_CLAIM = false;

inline constexpr std::string_view MODE = "synthetic-principal-v1";
inline constexpr std::string_view SOURCE_FINGERPRINT =
  "0ec0cb8527a709a935b638b946ad1e17f61636c6be41624c4a2baa23bac96248";

inline constexpr std::array<uint8_t, 32> AJTAI_SEED{{
  0x71, 0x73, 0x11, 0x44, 0xe4, 0x33, 0x7c, 0xb3,
  0x7c, 0x90, 0xf1, 0xbd, 0x3f, 0x79, 0x96, 0x2e,
  0x2f, 0x48, 0x23, 0x72, 0xca, 0x86, 0xf5, 0x41,
  0xea, 0xc5, 0x2e, 0x8c, 0x61, 0xcb, 0xc7, 0x57,
}};

inline constexpr std::array<uint8_t, 32> ORACLE_SEED{{
  0x60, 0xc4, 0x85, 0x67, 0xc5, 0x60, 0x23, 0xc1,
  0xcd, 0xd4, 0x7c, 0xef, 0x6d, 0xa9, 0x56, 0x75,
  0xea, 0x53, 0x67, 0x2b, 0x15, 0xbf, 0xa1, 0xbb,
  0x72, 0xf8, 0x09, 0x12, 0xb8, 0x5e, 0x96, 0xf1,
}};

// SHA3-256 of the textual built-in statement descriptor.  The protocol's
// canonical oracle seed additionally binds all instantiated constraints and
// public parameters directly.
inline constexpr std::array<uint8_t, 32> PUBLIC_DIGEST{{
  0xc9, 0x89, 0x5f, 0xee, 0x75, 0x30, 0x71, 0x54,
  0x06, 0xb7, 0xb2, 0x08, 0x9e, 0x2f, 0x9b, 0xfc,
  0xb2, 0xb0, 0x42, 0xa9, 0x4e, 0x7e, 0xed, 0xe0,
  0x0e, 0x64, 0xbd, 0xbe, 0xb0, 0x14, 0x50, 0x5b,
}};

} // namespace labrador_sample7
